# Generated by Django 3.0.7 on 2020-10-13 18:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCPA_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateTimeField(auto_now_add=True)),
                ('brand_name', models.CharField(max_length=100)),
                ('competitor_name1', models.CharField(blank=True, max_length=100, null=True)),
                ('competitor_name2', models.CharField(blank=True, max_length=100, null=True)),
                ('competitor_name3', models.CharField(blank=True, max_length=100, null=True)),
                ('competitor_name4', models.CharField(blank=True, max_length=100, null=True)),
                ('competitor_name5', models.CharField(blank=True, max_length=100, null=True)),
                ('competitor_name6', models.CharField(blank=True, max_length=100, null=True)),
                ('competitor_name7', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='HQ_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('dr_speciality', models.CharField(choices=[('NEUROLOGIST', 'NEUROLOGIST'), ('NEUROSURGEON', 'NEUROSURGEON'), ('PSYCHIATRIST', 'PSYCHIATRIST'), ('PHYSICIAN', 'PHYSICIAN'), ('GENRAL PHYSICIAN', 'GENRAL PHYSICIAN'), ('GYNAECOLOGIST', 'GYNAECOLOGIST'), ('SURGEON', 'SURGEON'), ('ORTHOLOGIST', 'ORTHOLOGIST')], max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('place', models.CharField(choices=[('HALDWANI', 'HALDWANI'), ('DEHRADUN', 'DEHRADUN'), ('MEERUT', 'MEERUT'), ('GAZIABAD', 'GAZIABAD'), ('KANPUR', 'KANPUR'), ('VARANAMSI', 'VARANAMSI'), ('JAMMU 1', 'JAMMU 1'), ('JAMMU 2', 'JAMMU 2'), ('AGRA', 'AGRA'), ('ALIGARH', 'ALIGARH'), ('GWALIOR', 'GWALIOR'), ('SHAHJANPUR', 'SHAHJANPUR'), ('BARIELLY', 'BARIELLY')], max_length=20)),
                ('current_doctor_business', models.FloatField(blank=True, max_length=100, null=True)),
                ('current_prescribing_brand', models.CharField(choices=[('CITOSYN-P', 'CITOSYN-P'), ('CITOSYN 2 ML', 'CITOSYN 2 ML'), ('CEFATRICS – S', 'CEFATRICS – S'), ('ESCITRICS PLUS', 'ESCITRICS PLUS'), ('LEVESYN', 'LEVESYN'), ('MEROTRICS 1 GM', 'MEROTRICS 1 GM'), ('NORISS', 'NORISS'), ('OLATRICS – 10 MG', 'OLATRICS – 10 MG'), ('OLATRICS – 2.5 MG', 'OLATRICS – 2.5 MG'), ('OLATRICS – 5 MG', 'OLATRICS – 5 MG'), ('PODOSYN – CV', 'PODOSYN – CV'), ('REVITRICS', 'REVITRICS'), ('SYNAC MR', 'SYNAC MR'), ('SYNAXONE INJ', 'SYNAXONE INJ'), ('SYNAZID TZ', 'SYNAZID TZ'), ('SYNAZOLE- R', 'SYNAZOLE- R'), ('SYNAZOLE DSR', 'SYNAZOLE DSR'), ('SYNERVE M', 'SYNERVE M'), ('VALSYN CR 300', 'VALSYN CR 300'), ('VALSYN CR 200', 'VALSYN CR 200'), ('VALSYN CR 500', 'VALSYN CR 500')], max_length=400)),
                ('brand_name1', models.CharField(blank=True, max_length=400, null=True)),
                ('brand_name2', models.CharField(blank=True, max_length=400, null=True)),
                ('brand_name3', models.CharField(blank=True, max_length=400, null=True)),
                ('brand_name4', models.CharField(blank=True, max_length=400, null=True)),
                ('brand_name5', models.CharField(blank=True, max_length=400, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('working_place', models.CharField(max_length=100)),
                ('calls_made', models.IntegerField()),
                ('chemist_meeting', models.IntegerField()),
                ('travelling_from', models.CharField(max_length=100)),
                ('travelling_to', models.CharField(max_length=100)),
                ('distance_travelled', models.IntegerField()),
                ('total_appointment', models.IntegerField()),
                ('daily_allowance', models.IntegerField()),
                ('telephone_internet_expenses', models.IntegerField()),
                ('total', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Dr_visit_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('dr_speciality', models.CharField(choices=[('NEUROLOGIST', 'NEUROLOGIST'), ('NEUROSURGEON', 'NEUROSURGEON'), ('PSYCHIATRIST', 'PSYCHIATRIST'), ('PHYSICIAN', 'PHYSICIAN'), ('GENRAL PHYSICIAN', 'GENRAL PHYSICIAN'), ('GYNAECOLOGIST', 'GYNAECOLOGIST'), ('SURGEON', 'SURGEON'), ('ORTHOLOGIST', 'ORTHOLOGIST')], max_length=100)),
                ('visit_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Dr_Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('dr_speciality', models.CharField(choices=[('NEUROLOGIST', 'NEUROLOGIST'), ('NEUROSURGEON', 'NEUROSURGEON'), ('PSYCHIATRIST', 'PSYCHIATRIST'), ('PHYSICIAN', 'PHYSICIAN'), ('GENRAL PHYSICIAN', 'GENRAL PHYSICIAN'), ('GYNAECOLOGIST', 'GYNAECOLOGIST'), ('SURGEON', 'SURGEON'), ('ORTHOLOGIST', 'ORTHOLOGIST')], max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(choices=[('JANUARY', 'JANUARY'), ('FEBURARY', 'FEBURARY'), ('MARCH', 'MARCH'), ('APRIL', 'APRIL'), ('MAY', 'MAY'), ('JUNE', 'JUNE'), ('JULY', 'JULY'), ('AUGUST', 'AUGUST'), ('SEPTEMBER', 'SEPTEMBER'), ('OCTOBER', 'OCTUBER'), ('NOVEMBER', 'NOVEMBER'), ('DECEMBER', 'DECEMBER')], max_length=20)),
                ('business', models.FloatField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='doctor_visit_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('dr_speciality', models.CharField(choices=[('NEUROLOGIST', 'NEUROLOGIST'), ('NEUROSURGEON', 'NEUROSURGEON'), ('PSYCHIATRIST', 'PSYCHIATRIST'), ('PHYSICIAN', 'PHYSICIAN'), ('GENRAL PHYSICIAN', 'GENRAL PHYSICIAN'), ('GYNAECOLOGIST', 'GYNAECOLOGIST'), ('SURGEON', 'SURGEON'), ('ORTHOLOGIST', 'ORTHOLOGIST')], max_length=100)),
                ('date_of_visit', models.DateTimeField(auto_now_add=True)),
                ('month', models.CharField(choices=[('JANUARY', 'JANUARY'), ('FEBURARY', 'FEBURARY'), ('MARCH', 'MARCH'), ('APRIL', 'APRIL'), ('MAY', 'MAY'), ('JUNE', 'JUNE'), ('JULY', 'JULY'), ('AUGUST', 'AUGUST'), ('SEPTEMBER', 'SEPTEMBER'), ('OCTOBER', 'OCTUBER'), ('NOVEMBER', 'NOVEMBER'), ('DECEMBER', 'DECEMBER')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='DirectHR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='day_summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_calls', models.IntegerField()),
                ('business_outcomes_of_total_calls', models.IntegerField()),
                ('total_chemist_meeting', models.IntegerField()),
                ('business_outcomes_of_total_metting', models.IntegerField()),
                ('report_submission', models.DateTimeField(auto_now_add=True)),
                ('delayed_submission', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='DailyWorkingReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=100)),
                ('dr_speciality', models.CharField(choices=[('NEUROLOGIST', 'NEUROLOGIST'), ('NEUROSURGEON', 'NEUROSURGEON'), ('PSYCHIATRIST', 'PSYCHIATRIST'), ('PHYSICIAN', 'PHYSICIAN'), ('GENRAL PHYSICIAN', 'GENRAL PHYSICIAN'), ('GYNAECOLOGIST', 'GYNAECOLOGIST'), ('SURGEON', 'SURGEON'), ('ORTHOLOGIST', 'ORTHOLOGIST')], max_length=100)),
                ('meeting_place', models.CharField(choices=[('DR CLINIC', 'DR CLINIC'), ('HOSPITAL', 'HOSPITAL'), ('RESIDENCE HOME ADDRESS', 'RESIDENCE HOME ADDRESS')], max_length=100)),
                ('Date_time', models.DateTimeField(auto_now=True)),
                ('prescrebtionBrand', models.CharField(max_length=100)),
                ('user_WorkingPlace', models.CharField(max_length=100)),
                ('current_month_business', models.IntegerField()),
                ('Daily_business_outcomes', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Daily_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THRUSDAY', 'THRUSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='chemistlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemist_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('place', models.CharField(choices=[('HALDWANI', 'HALDWANI'), ('DEHRADUN', 'DEHRADUN'), ('MEERUT', 'MEERUT'), ('GAZIABAD', 'GAZIABAD'), ('KANPUR', 'KANPUR'), ('VARANAMSI', 'VARANAMSI'), ('JAMMU 1', 'JAMMU 1'), ('JAMMU 2', 'JAMMU 2'), ('AGRA', 'AGRA'), ('ALIGARH', 'ALIGARH'), ('GWALIOR', 'GWALIOR'), ('SHAHJANPUR', 'SHAHJANPUR'), ('BARIELLY', 'BARIELLY')], max_length=20)),
                ('POB_Collection_status', models.FloatField(blank=True, max_length=100, null=True)),
                ('ABM_Approach_Status', models.CharField(blank=True, max_length=400, null=True)),
                ('brand_name1', models.CharField(blank=True, max_length=400, null=True)),
                ('brand_name2', models.CharField(blank=True, max_length=400, null=True)),
                ('brand_name3', models.CharField(blank=True, max_length=400, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='chemist_call_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemist_name', models.CharField(max_length=100)),
                ('business_outcomes_chemist_visit', models.IntegerField()),
                ('date_of_visit', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
