# Generated by Django 3.0.7 on 2020-10-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20201014_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drmasterlist',
            name='business',
        ),
        migrations.AddField(
            model_name='drmasterlist',
            name='brand_promotion_plan',
            field=models.CharField(choices=[('Brand1', 'Brand1'), ('Brand2', 'Brand2'), ('Brand3', 'Brand3'), ('Brand4', 'Brand4'), ('Brand5', 'Brand5')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drmasterlist',
            name='current_business',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drmasterlist',
            name='current_prescribing_brand',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
