# Generated by Django 3.0.7 on 2020-10-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_chemistmasterlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavehr',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
