# Generated by Django 3.0.7 on 2020-10-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_leavehr_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemistlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='daily_plan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dailyworkingreport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='day_summary',
            name='user',
        ),
        migrations.RemoveField(
            model_name='doctor_visit_report',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dr_visit_report',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hq_list',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rcpa_details',
            name='user',
        ),
        migrations.DeleteModel(
            name='chemist_call_report',
        ),
        migrations.DeleteModel(
            name='chemistlist',
        ),
        migrations.DeleteModel(
            name='Daily_plan',
        ),
        migrations.DeleteModel(
            name='DailyWorkingReport',
        ),
        migrations.DeleteModel(
            name='day_summary',
        ),
        migrations.DeleteModel(
            name='doctor_visit_report',
        ),
        migrations.DeleteModel(
            name='Dr_visit_report',
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
        migrations.DeleteModel(
            name='HQ_List',
        ),
        migrations.DeleteModel(
            name='RCPA_details',
        ),
    ]
