# Generated by Django 3.0.7 on 2020-10-15 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20201015_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivites',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
