# Generated by Django 3.1 on 2020-10-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_dailyactivites_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkingReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=100)),
                ('dr_speciality', models.CharField(choices=[('NEUROLOGIST', 'NEUROLOGIST'), ('NEUROSURGEON', 'NEUROSURGEON'), ('PSYCHIATRIST', 'PSYCHIATRIST'), ('PHYSICIAN', 'PHYSICIAN'), ('GENRAL PHYSICIAN', 'GENRAL PHYSICIAN'), ('GYNAECOLOGIST', 'GYNAECOLOGIST'), ('SURGEON', 'SURGEON'), ('ORTHOLOGIST', 'ORTHOLOGIST')], max_length=100)),
                ('meeting_place', models.CharField(choices=[('DR CLINIC', 'DR CLINIC'), ('HOSPITAL', 'HOSPITAL'), ('RESIDENCE HOME ADDRESS', 'RESIDENCE HOME ADDRESS')], max_length=100)),
                ('Date_time', models.DateTimeField(auto_now=True)),
                ('prescrebtionBrand', models.CharField(max_length=100)),
                ('user_WorkingPlace', models.CharField(max_length=100)),
                ('current_month_business', models.IntegerField()),
                ('Daily_business_outcomes', models.IntegerField()),
            ],
        ),
    ]
