# Generated by Django 3.1 on 2020-10-15 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_dailyworkingreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkingreport',
            name='dr_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.drmasterlist'),
        ),
    ]
