# Generated by Django 3.1 on 2020-10-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20201015_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyWorkingReport',
            new_name='DailyDrcallReport',
        ),
    ]
