# Generated by Django 3.1 on 2020-10-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_auto_20201015_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydrcallreport',
            name='Daily_business_outcomes',
        ),
    ]
