# Generated by Django 3.1 on 2020-10-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_remove_dailydrcallreport_daily_business_outcomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydrcallreport',
            name='prescrebtionBrand',
            field=models.CharField(choices=[('Brand1', 'Brand1'), ('Brand2', 'Brand2'), ('Brand3', 'Brand3'), ('Brand4', 'Brand4'), ('Brand5', 'Brand5')], max_length=100),
        ),
    ]
