# Generated by Django 3.0.7 on 2020-10-15 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('report', '0018_others'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydrcallreport',
            name='meeting_place',
        ),
        migrations.RemoveField(
            model_name='dailydrcallreport',
            name='prescrebtionBrand',
        ),
        migrations.RemoveField(
            model_name='dailydrcallreport',
            name='user_WorkingPlace',
        ),
        migrations.AddField(
            model_name='dailydrcallreport',
            name='Place',
            field=models.CharField(choices=[('HALDWANI', 'HALDWANI'), ('DEHRADUN', 'DEHRADUN'), ('MEERUT', 'MEERUT'), ('GAZIABAD', 'GAZIABAD'), ('KANPUR', 'KANPUR'), ('VARANAMSI', 'VARANAMSI'), ('JAMMU 1', 'JAMMU 1'), ('JAMMU 2', 'JAMMU 2'), ('AGRA', 'AGRA'), ('ALIGARH', 'ALIGARH'), ('GWALIOR', 'GWALIOR'), ('SHAHJANPUR', 'SHAHJANPUR'), ('BARIELLY', 'BARIELLY')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailydrcallreport',
            name='brand_name1',
            field=models.CharField(choices=[('CITOSYN-P', 'CITOSYN-P'), ('CITOSYN 2 ML', 'CITOSYN 2 ML'), ('CEFATRICS – S', 'CEFATRICS – S'), ('ESCITRICS PLUS', 'ESCITRICS PLUS'), ('LEVESYN', 'LEVESYN'), ('MEROTRICS 1 GM', 'MEROTRICS 1 GM'), ('NORISS', 'NORISS'), ('OLATRICS – 10 MG', 'OLATRICS – 10 MG'), ('OLATRICS – 2.5 MG', 'OLATRICS – 2.5 MG'), ('OLATRICS – 5 MG', 'OLATRICS – 5 MG'), ('PODOSYN – CV', 'PODOSYN – CV'), ('REVITRICS', 'REVITRICS'), ('SYNAC MR', 'SYNAC MR'), ('SYNAXONE INJ', 'SYNAXONE INJ'), ('SYNAZID TZ', 'SYNAZID TZ'), ('SYNAZOLE- R', 'SYNAZOLE- R'), ('SYNAZOLE DSR', 'SYNAZOLE DSR'), ('SYNERVE M', 'SYNERVE M'), ('VALSYN CR 300', 'VALSYN CR 300'), ('VALSYN CR 200', 'VALSYN CR 200'), ('VALSYN CR 500', 'VALSYN CR 500')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailydrcallreport',
            name='brand_name2',
            field=models.CharField(choices=[('CITOSYN-P', 'CITOSYN-P'), ('CITOSYN 2 ML', 'CITOSYN 2 ML'), ('CEFATRICS – S', 'CEFATRICS – S'), ('ESCITRICS PLUS', 'ESCITRICS PLUS'), ('LEVESYN', 'LEVESYN'), ('MEROTRICS 1 GM', 'MEROTRICS 1 GM'), ('NORISS', 'NORISS'), ('OLATRICS – 10 MG', 'OLATRICS – 10 MG'), ('OLATRICS – 2.5 MG', 'OLATRICS – 2.5 MG'), ('OLATRICS – 5 MG', 'OLATRICS – 5 MG'), ('PODOSYN – CV', 'PODOSYN – CV'), ('REVITRICS', 'REVITRICS'), ('SYNAC MR', 'SYNAC MR'), ('SYNAXONE INJ', 'SYNAXONE INJ'), ('SYNAZID TZ', 'SYNAZID TZ'), ('SYNAZOLE- R', 'SYNAZOLE- R'), ('SYNAZOLE DSR', 'SYNAZOLE DSR'), ('SYNERVE M', 'SYNERVE M'), ('VALSYN CR 300', 'VALSYN CR 300'), ('VALSYN CR 200', 'VALSYN CR 200'), ('VALSYN CR 500', 'VALSYN CR 500')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailydrcallreport',
            name='brand_name3',
            field=models.CharField(choices=[('CITOSYN-P', 'CITOSYN-P'), ('CITOSYN 2 ML', 'CITOSYN 2 ML'), ('CEFATRICS – S', 'CEFATRICS – S'), ('ESCITRICS PLUS', 'ESCITRICS PLUS'), ('LEVESYN', 'LEVESYN'), ('MEROTRICS 1 GM', 'MEROTRICS 1 GM'), ('NORISS', 'NORISS'), ('OLATRICS – 10 MG', 'OLATRICS – 10 MG'), ('OLATRICS – 2.5 MG', 'OLATRICS – 2.5 MG'), ('OLATRICS – 5 MG', 'OLATRICS – 5 MG'), ('PODOSYN – CV', 'PODOSYN – CV'), ('REVITRICS', 'REVITRICS'), ('SYNAC MR', 'SYNAC MR'), ('SYNAXONE INJ', 'SYNAXONE INJ'), ('SYNAZID TZ', 'SYNAZID TZ'), ('SYNAZOLE- R', 'SYNAZOLE- R'), ('SYNAZOLE DSR', 'SYNAZOLE DSR'), ('SYNERVE M', 'SYNERVE M'), ('VALSYN CR 300', 'VALSYN CR 300'), ('VALSYN CR 200', 'VALSYN CR 200'), ('VALSYN CR 500', 'VALSYN CR 500')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailydrcallreport',
            name='brand_name4',
            field=models.CharField(choices=[('CITOSYN-P', 'CITOSYN-P'), ('CITOSYN 2 ML', 'CITOSYN 2 ML'), ('CEFATRICS – S', 'CEFATRICS – S'), ('ESCITRICS PLUS', 'ESCITRICS PLUS'), ('LEVESYN', 'LEVESYN'), ('MEROTRICS 1 GM', 'MEROTRICS 1 GM'), ('NORISS', 'NORISS'), ('OLATRICS – 10 MG', 'OLATRICS – 10 MG'), ('OLATRICS – 2.5 MG', 'OLATRICS – 2.5 MG'), ('OLATRICS – 5 MG', 'OLATRICS – 5 MG'), ('PODOSYN – CV', 'PODOSYN – CV'), ('REVITRICS', 'REVITRICS'), ('SYNAC MR', 'SYNAC MR'), ('SYNAXONE INJ', 'SYNAXONE INJ'), ('SYNAZID TZ', 'SYNAZID TZ'), ('SYNAZOLE- R', 'SYNAZOLE- R'), ('SYNAZOLE DSR', 'SYNAZOLE DSR'), ('SYNERVE M', 'SYNERVE M'), ('VALSYN CR 300', 'VALSYN CR 300'), ('VALSYN CR 200', 'VALSYN CR 200'), ('VALSYN CR 500', 'VALSYN CR 500')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailydrcallreport',
            name='brand_name5',
            field=models.CharField(choices=[('CITOSYN-P', 'CITOSYN-P'), ('CITOSYN 2 ML', 'CITOSYN 2 ML'), ('CEFATRICS – S', 'CEFATRICS – S'), ('ESCITRICS PLUS', 'ESCITRICS PLUS'), ('LEVESYN', 'LEVESYN'), ('MEROTRICS 1 GM', 'MEROTRICS 1 GM'), ('NORISS', 'NORISS'), ('OLATRICS – 10 MG', 'OLATRICS – 10 MG'), ('OLATRICS – 2.5 MG', 'OLATRICS – 2.5 MG'), ('OLATRICS – 5 MG', 'OLATRICS – 5 MG'), ('PODOSYN – CV', 'PODOSYN – CV'), ('REVITRICS', 'REVITRICS'), ('SYNAC MR', 'SYNAC MR'), ('SYNAXONE INJ', 'SYNAXONE INJ'), ('SYNAZID TZ', 'SYNAZID TZ'), ('SYNAZOLE- R', 'SYNAZOLE- R'), ('SYNAZOLE DSR', 'SYNAZOLE DSR'), ('SYNERVE M', 'SYNERVE M'), ('VALSYN CR 300', 'VALSYN CR 300'), ('VALSYN CR 200', 'VALSYN CR 200'), ('VALSYN CR 500', 'VALSYN CR 500')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailydrcallreport',
            name='current_prescribing_brand',
            field=models.CharField(choices=[('CITOSYN-P', 'CITOSYN-P'), ('CITOSYN 2 ML', 'CITOSYN 2 ML'), ('CEFATRICS – S', 'CEFATRICS – S'), ('ESCITRICS PLUS', 'ESCITRICS PLUS'), ('LEVESYN', 'LEVESYN'), ('MEROTRICS 1 GM', 'MEROTRICS 1 GM'), ('NORISS', 'NORISS'), ('OLATRICS – 10 MG', 'OLATRICS – 10 MG'), ('OLATRICS – 2.5 MG', 'OLATRICS – 2.5 MG'), ('OLATRICS – 5 MG', 'OLATRICS – 5 MG'), ('PODOSYN – CV', 'PODOSYN – CV'), ('REVITRICS', 'REVITRICS'), ('SYNAC MR', 'SYNAC MR'), ('SYNAXONE INJ', 'SYNAXONE INJ'), ('SYNAZID TZ', 'SYNAZID TZ'), ('SYNAZOLE- R', 'SYNAZOLE- R'), ('SYNAZOLE DSR', 'SYNAZOLE DSR'), ('SYNERVE M', 'SYNERVE M'), ('VALSYN CR 300', 'VALSYN CR 300'), ('VALSYN CR 200', 'VALSYN CR 200'), ('VALSYN CR 500', 'VALSYN CR 500')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailydrcallreport',
            name='Date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailydrcallreport',
            name='current_month_business',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydrcallreport',
            name='dr_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.DrMasterList'),
        ),
        migrations.AlterField(
            model_name='dailydrcallreport',
            name='dr_speciality',
            field=models.CharField(choices=[('NEUROLOGIST', 'NEUROLOGIST'), ('NEUROSURGEON', 'NEUROSURGEON'), ('PSYCHIATRIST', 'PSYCHIATRIST'), ('PHYSICIAN', 'PHYSICIAN'), ('GENRAL PHYSICIAN', 'GENRAL PHYSICIAN'), ('GYNAECOLOGIST', 'GYNAECOLOGIST'), ('SURGEON', 'SURGEON'), ('ORTHOLOGIST', 'ORTHOLOGIST')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailydrmeetingreport',
            name='Date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailydrmeetingreport',
            name='dr_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.DrMasterList'),
        ),
        migrations.AlterField(
            model_name='dailydrmeetingreport',
            name='dr_speciality',
            field=models.CharField(choices=[('NEUROLOGIST', 'NEUROLOGIST'), ('NEUROSURGEON', 'NEUROSURGEON'), ('PSYCHIATRIST', 'PSYCHIATRIST'), ('PHYSICIAN', 'PHYSICIAN'), ('GENRAL PHYSICIAN', 'GENRAL PHYSICIAN'), ('GYNAECOLOGIST', 'GYNAECOLOGIST'), ('SURGEON', 'SURGEON'), ('ORTHOLOGIST', 'ORTHOLOGIST')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailydrmeetingreport',
            name='meeting_place',
            field=models.CharField(choices=[('DR CLINIC', 'DR CLINIC'), ('HOSPITAL', 'HOSPITAL'), ('RESIDENCE HOME ADDRESS', 'RESIDENCE HOME ADDRESS')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DailyChemistcallReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_time', models.DateTimeField(auto_now=True, null=True)),
                ('mobile', models.IntegerField()),
                ('brand_name1', models.CharField(choices=[('CITOSYN-P', 'CITOSYN-P'), ('CITOSYN 2 ML', 'CITOSYN 2 ML'), ('CEFATRICS – S', 'CEFATRICS – S'), ('ESCITRICS PLUS', 'ESCITRICS PLUS'), ('LEVESYN', 'LEVESYN'), ('MEROTRICS 1 GM', 'MEROTRICS 1 GM'), ('NORISS', 'NORISS'), ('OLATRICS – 10 MG', 'OLATRICS – 10 MG'), ('OLATRICS – 2.5 MG', 'OLATRICS – 2.5 MG'), ('OLATRICS – 5 MG', 'OLATRICS – 5 MG'), ('PODOSYN – CV', 'PODOSYN – CV'), ('REVITRICS', 'REVITRICS'), ('SYNAC MR', 'SYNAC MR'), ('SYNAXONE INJ', 'SYNAXONE INJ'), ('SYNAZID TZ', 'SYNAZID TZ'), ('SYNAZOLE- R', 'SYNAZOLE- R'), ('SYNAZOLE DSR', 'SYNAZOLE DSR'), ('SYNERVE M', 'SYNERVE M'), ('VALSYN CR 300', 'VALSYN CR 300'), ('VALSYN CR 200', 'VALSYN CR 200'), ('VALSYN CR 500', 'VALSYN CR 500')], max_length=100, null=True)),
                ('brand_name2', models.CharField(choices=[('CITOSYN-P', 'CITOSYN-P'), ('CITOSYN 2 ML', 'CITOSYN 2 ML'), ('CEFATRICS – S', 'CEFATRICS – S'), ('ESCITRICS PLUS', 'ESCITRICS PLUS'), ('LEVESYN', 'LEVESYN'), ('MEROTRICS 1 GM', 'MEROTRICS 1 GM'), ('NORISS', 'NORISS'), ('OLATRICS – 10 MG', 'OLATRICS – 10 MG'), ('OLATRICS – 2.5 MG', 'OLATRICS – 2.5 MG'), ('OLATRICS – 5 MG', 'OLATRICS – 5 MG'), ('PODOSYN – CV', 'PODOSYN – CV'), ('REVITRICS', 'REVITRICS'), ('SYNAC MR', 'SYNAC MR'), ('SYNAXONE INJ', 'SYNAXONE INJ'), ('SYNAZID TZ', 'SYNAZID TZ'), ('SYNAZOLE- R', 'SYNAZOLE- R'), ('SYNAZOLE DSR', 'SYNAZOLE DSR'), ('SYNERVE M', 'SYNERVE M'), ('VALSYN CR 300', 'VALSYN CR 300'), ('VALSYN CR 200', 'VALSYN CR 200'), ('VALSYN CR 500', 'VALSYN CR 500')], max_length=100, null=True)),
                ('brand_name3', models.CharField(choices=[('CITOSYN-P', 'CITOSYN-P'), ('CITOSYN 2 ML', 'CITOSYN 2 ML'), ('CEFATRICS – S', 'CEFATRICS – S'), ('ESCITRICS PLUS', 'ESCITRICS PLUS'), ('LEVESYN', 'LEVESYN'), ('MEROTRICS 1 GM', 'MEROTRICS 1 GM'), ('NORISS', 'NORISS'), ('OLATRICS – 10 MG', 'OLATRICS – 10 MG'), ('OLATRICS – 2.5 MG', 'OLATRICS – 2.5 MG'), ('OLATRICS – 5 MG', 'OLATRICS – 5 MG'), ('PODOSYN – CV', 'PODOSYN – CV'), ('REVITRICS', 'REVITRICS'), ('SYNAC MR', 'SYNAC MR'), ('SYNAXONE INJ', 'SYNAXONE INJ'), ('SYNAZID TZ', 'SYNAZID TZ'), ('SYNAZOLE- R', 'SYNAZOLE- R'), ('SYNAZOLE DSR', 'SYNAZOLE DSR'), ('SYNERVE M', 'SYNERVE M'), ('VALSYN CR 300', 'VALSYN CR 300'), ('VALSYN CR 200', 'VALSYN CR 200'), ('VALSYN CR 500', 'VALSYN CR 500')], max_length=100, null=True)),
                ('Place', models.CharField(choices=[('HALDWANI', 'HALDWANI'), ('DEHRADUN', 'DEHRADUN'), ('MEERUT', 'MEERUT'), ('GAZIABAD', 'GAZIABAD'), ('KANPUR', 'KANPUR'), ('VARANAMSI', 'VARANAMSI'), ('JAMMU 1', 'JAMMU 1'), ('JAMMU 2', 'JAMMU 2'), ('AGRA', 'AGRA'), ('ALIGARH', 'ALIGARH'), ('GWALIOR', 'GWALIOR'), ('SHAHJANPUR', 'SHAHJANPUR'), ('BARIELLY', 'BARIELLY')], max_length=100, null=True)),
                ('chemist_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.ChemistMasterList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
