# Generated by Django 3.0.7 on 2020-10-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_auto_20201016_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydrcallreport',
            name='workwith',
            field=models.CharField(choices=[('ALONE', 'ALONE'), ('ABM', 'ABM'), ('RBM', 'RBM'), ('ZBM', 'ZBM')], max_length=10, null=True),
        ),
    ]
