# Generated by Django 3.0.7 on 2020-10-15 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('report', '0020_dailydrcallreport_workwith'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('calls_made', models.IntegerField()),
                ('chemist_meeting', models.IntegerField()),
                ('travelling_from', models.CharField(max_length=100)),
                ('travelling_to', models.CharField(max_length=100)),
                ('distance_travelled', models.IntegerField()),
                ('total_appointment', models.IntegerField()),
                ('daily_allowance', models.IntegerField()),
                ('telephone_internet_expenses', models.IntegerField()),
                ('total', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
