# Generated by Django 3.0.7 on 2020-10-20 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201020_0839'),
        ('report', '0023_monthlyplan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaveHR',
            new_name='LeaveHRForm',
        ),
    ]
