# Generated by Django 3.0.7 on 2020-10-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='pan_pic',
            field=models.FileField(upload_to=''),
        ),
    ]
